### ISSUE TITLE
Failed Deposit Into Ionic

### ISSUE THREAD

**Issue by benjoch** [gizatechxyz/arma_feedback#3]
### Description of the issue

I had just activated my agent and deposited 4364.37 USDC. The agent attempted to submit to Ionic USDC Pool but the transaction failed

My Wallet Address: 0x5F38305c7583c269F1b89087101C9e65D605BFeb

### Correlation ID

869bc9592ad74feeb13ce840dc4c1bf1

### Expected behavior

Successful deposit into Ionic

**Comment by franalgaba** [comment]
Hi @benjoch ! Thanks a lot for the patience and apologies for the inconvenience. The issue should be now resolved if you check again your dashboard. There was an inconsistency in the database that tracks the transactions, your funds are safe and correctly allocated with the agent. Let us know if we can help you with anything else :)

**Comment by benjoch** [comment]
The issued is resolved on my end now! No problem - thanks for the timely response and help!
